### ISSUE TITLE
Allow configuration of multiple rules

### ISSUE THREAD

**Issue by bobvanderlinden** [bobvanderlinden/probot-auto-merge#17]
Currently it is only possible to combine a number of conditions and they all must be true before a merge is started. There are use-cases where some condition may overrule all other conditions.

An example of such a use-case is a repository owner who wants all PRs automatically merged when a merge label is added. In other cases it will be automatically merged when 2 collaborators have approved the PR.

An initial proposal for the configuration:

```yaml
rules:
- minApprovals:
    COLLABORATOR: 2
- requiredLabels:
  - merge
```

What might also be useful is to still allow global conditions that should be true regardless of the different rules. For instance requested changes might overrule all other conditions. This would look like:

```yaml
maxRequestedChanges:
  COLLABORATOR: 1

rules:
- minApprovals:
    COLLABORATOR: 2
- requiredLabels:
  - merge
```

This makes the configuration much more flexible and should cover most use-cases.
