### ISSUE TITLE
Number of approvals depending on PR author

### ISSUE THREAD

**Issue by dpo** [bobvanderlinden/probot-auto-merge#707]
Many thanks for providing this bot! I have a question on the configuration of the min number of approvals.

How does one request 2 owner approvals for PRs submitted by a non-owner and 1 owner approval for PRs submitted by an (other) owner?

Thanks!

**Comment by bobvanderlinden** [comment]
This is not clearly supported, but you can use multiple rules:

```
rules:
  - minApprovals:
      OWNER: 2
  - minApprovals:
    OWNER: 1
    MEMBER: 1
```

Something like this. If any rule matches, auto-merge will attempt to merge.

**Comment by abelsiqueira** [comment]
I'm not sure works for our intended purposes. We're the main devs of a package. When one submits a PR and the other approves, we'd like for it to be automatically merged after CI. However, if someone else submits the PR, then both of us should approve for an automatic merge.
This usually happens when we review before the CI is over (CI takes over an hour).

**Comment by bobvanderlinden** [comment]
Aah, so it depends on the role of the owner of the PR? Hmm, you're indeed right that this is not currently supported, but it does seem like a valid use-case.

I'm imagining something like a `pullRequestOwnerRole` setting that might help:

```
rules:
  - pullRequestOwnerRole: MEMBER
    minApprovals:
      MEMBER: 1
  - minApprovals:
      MEMBER: 2
```
