### ISSUE TITLE
[Documentation] "rules" usage is not clear

### ISSUE THREAD

**Issue by rogerluan** [bobvanderlinden/probot-auto-merge#815]
Hey again 😁 

In my project, I'd like to write some sort of complex sets of `rules`. However, it's not clear how the `rules` condition should be used.

My goal was something like this: `rules: (condition1 && condition2) || (condition3 && condition4)`

To achieve that, I would write something like this:

```yaml
rules:
- condition1 (where would I put the condition2?)
- condition3 (where would I put the condition4?)
```

Is this type of rule construction even possible, or only a single-level OR rules like `rules: condition1 || condition2`?

Is this a valid syntax? → 

```yaml
rules:
- rules:
  - condition1
  - condition2
- rules:
  - condition3
  - condition4
```

If so, that would solve the issue, as that would semantically characterize as `(condition1 && condition2) || (condition3 && condition4)`.

…However, on top of my config file understanding issues, I was playing around with the `rules` and keep facing error 500s whenever I try to set some rules, for instance:

```yaml
rules:
- minApprovals:
  MEMBER: 2
- minApprovals:
  CONTRIBUTOR: 2
```

I get HTTP 500: `Error: Webhook handler error` 🤔 

Any help would be very much appreciated! Again, thank you so much for all the hard work on putting this bot together. The more I dive into the code, the more I like it :) it's very well structured. 

Cheers!

**Comment by bobvanderlinden** [comment]
auto-merge doesn't do `&&`. Only `||`. If one of the rules succeeds the PR gets merged.
You can consider the global configuration as a separate rule.

If you want to do something like `(condition1 && condition2) || (condition3 && condition4)` then I would suggest creating 2 rules: one merging `condition1` and `condition2` and the other merging `condition3` and `condition4`.

If that isn't clear, let me know the exact use-case.

The example you gave is incorrect, due to `MEMBER` needing to be inside `minApprovals` (in your example it is next to `minApprovals`). So:

```yaml
rules:
- minApprovals:
    MEMBER: 2
- minApprovals:
    CONTRIBUTOR: 2
```

In this specific case, `CONTRIBUTOR` is a 'lower' role compared to `MEMBER`, so if you're specifying:

```yaml
minApprovals:
  CONTRIBUTOR: 2
```

You're also allowing `MEMBER` and `OWNER` as those are also considered to be contributors. This was done because allowing approvals from contributors did not (surprisingly for most people) allow merging by approvals of the owner, even though the owner is also considered a contributor and member.

The implementation is here: https://github.com/bobvanderlinden/probot-auto-merge/blob/master/src/association.ts

**Comment by rogerluan** [comment]
Ooh got it! Pardon my ignorance, the error 500 was due to syntax issues in the yaml file then (lack of indentation) 🙈 

> I would suggest creating 2 rules: one merging condition1 and condition2 and the other merging condition3 and condition4.
>If that isn't clear, let me know the exact use-case.

It's still not clear how I'd achieve that 😬 the use case would be alongside the new `requiredReviewers` option added in https://github.com/bobvanderlinden/probot-auto-merge/pull/813 

I'd like to allow something like:

```
merge if 3 MEMBERS || 1 MEMBER && rogerluan || 1 MEMBER && bobvanderlinden || bobvanderlinden && rogerluan
```

**Comment by bobvanderlinden** [comment]
That would be something like:

```yaml
rules:
- minApprovals:
    MEMBER: 3
- minApprovals:
    MEMBER: 2
  requiredReviewers:
  - rogerluan
- minApprovals:
    MEMBER: 2
  requiredReviewers:
  - bobvanderlinden
- requiredReviewers:
  - bobvanderlinden
  - rogerluan
```

Do note that `1 MEMBER && rogerluan` isn't really correct, as you mean "rogerluan and 1 _other_ member", but we cannot specify the "other" part. Since rogerluan can be considered a member, I changed it to rogerluan and 2 members.
