### ISSUE TITLE
Failing branch merged

### ISSUE THREAD

**Issue by tamj0rd2** [bobvanderlinden/probot-auto-merge#834]
I just had a bad commit merged and I'm not sure why it happened. This travis check is a required check

![image](https://user-images.githubusercontent.com/20561445/91437382-b7b84500-e861-11ea-81b0-feada8d6c57c.png)

The PR: https://github.com/tamj0rd2/ncdc/pull/386#event-3699185702

Config:

```yaml
blockingLabels:
  - dependencies
requiredLabels:
  - merge
blockingTitleRegex: '\bWIP\b'
mergeMethod: rebase
reportStatus: true
```

I've set up my config so that only pull requests with the `merge` label will get merged, but I thought that all required checks would still need to pass first?
