### ISSUE TITLE
Auto Merge not processing PR's

### ISSUE THREAD

**Issue by rolandoldengarm** [bobvanderlinden/probot-auto-merge#842]
I've installed auto-merge today and filled out the auto-merge.yml file, I've added it to the .github folder. However, PR's are not being merged, despite them meeting the requirements. My `auto-merge.yml` is as follows (I've removed the comments):

```
minApprovals:
  MEMBER: 2
  COLLABORATOR: 2

maxRequestedChanges:
  COLLABORATOR: 0
  MEMBER: 0

updateBranch: true
deleteBranchAfterMerge: true
mergeMethod: squash
mergeCommitMessage: |
  {title} (#{number})

  {body}
requiredBaseBranches:
  - qa

blockingLabels:
  - blocked

requiredLabels:
  - merge
```

A PR is ready to be merged and meets the requirements, but nothing happens:
![image](https://user-images.githubusercontent.com/14539000/92196670-dce12f00-eec3-11ea-8310-905fb0c2baff.png)
![image](https://user-images.githubusercontent.com/14539000/92196645-ca66f580-eec3-11ea-8022-eb791e275987.png)
![image](https://user-images.githubusercontent.com/14539000/92196735-069a5600-eec4-11ea-83bd-23b11c8a1bb4.png)

Why isn't it being merged?
