### ISSUE TITLE
Add option to block if not all reviewers have approved

### ISSUE THREAD

**Issue by tvuotila** [bobvanderlinden/probot-auto-merge#853]
Use case: When we create a PR, we request review from one or two peers. It would be nice to wait for all of them to approve the PR before merging.

Solution proposal: Add option "maxPendingReviews". Settings that to 0 would require all of the reviewers to either approve or request changes to the PR. Combining it with setting "maxRequestedChanges" to 0 would require every reviewer to approve the PR.

For example
```
minApprovals:
  NONE: 1
maxRequestedChanges:
  NONE: 0
maxPendingReviews:
  NONE: 0
```
