### ISSUE TITLE
Allow rules to use pull request author as a config value

### ISSUE THREAD

**Issue by mauroservienti** [bobvanderlinden/probot-auto-merge#862]
This is related to #707

I'm using the following configuration (sample source: https://github.com/mauroservienti/welcome-to-the-state-machine-demos/blob/master/.github/auto-merge.yml):

```
minApprovals:
  OWNER: 1
  
# must be enabled as a merge option in the repository settings
mergeMethod: squash

# report bot status details as a check on the PR
reportStatus: true

deleteBranchAfterMerge: true

blockingLabels:
- blocked
```

I'm also relying on dependabot to keep dependencies up-to-date. One thing I'd like to be able to do is to auto-merge green PRs from a specific author, in this case dependabot, without any required approval. Something like the following:

```
rules:
- requiredAuthor: app/dependabot
  minApprovals:
    NONE: 0
```

Would it be possible?

**Comment by bobvanderlinden** [comment]
I think this should do what you're asking:

```
rules:
- requiredAuthor: app/dependabot
  minApprovals:
    NONE: 0
- minApprovals:
    OWNER: 1
```
