### ISSUE TITLE
Bot tries to also handle old closed and merged pull_requests and runs into errors

### ISSUE THREAD

**Issue by roydenwa** [bobvanderlinden/probot-auto-merge#886]
The bot is used in a large repo with the following simple config:
```YAML
blockingLabels:
- 'SKIP ALL'

requiredLabels:
- AutoMerge

deleteBranchAfterMerge: true

mergeMethod: squash
```
The error logs suggest that the bot is also trying to handle old closed and merged pull_requests. 
Could this unwanted behavior be due to the fact that the `getAssosiatedPullRequests` function in `index.ts` sometimes returns all pull_requests for a certain repo?
