### ISSUE TITLE
Rules seem to be not respected

### ISSUE THREAD

**Issue by mauroservienti** [bobvanderlinden/probot-auto-merge#927]
I use the following configuration

```
rules:
- requiredAuthor: dependabot
  minApprovals:
    NONE: 0
- minApprovals:
    OWNER: 1
  
# must be enabled as a merge option in the repository settings
mergeMethod: squash

# report bot status details as a check on the PR
reportStatus: true

deleteBranchAfterMerge: true

blockingLabels:
- blocked
```

([source](https://github.com/mauroservienti/all-our-aggregates-are-wrong-demos/blob/master/.github/auto-merge.yml))

My goal is to auto-merge ONLY `dependabot` pull requests. I seem to be failing at that, all pull requests are merged regardless of what I set in the configuration. Any help is appreciated.
