### ISSUE TITLE
minimumApprovals is never checked

### ISSUE THREAD

**Issue by stefdelec** [bobvanderlinden/probot-auto-merge#992]
I have my config as:

```

updateBranch: true
deleteBranchAfterMerge: true
reportStatus: true

minApprovals:
  CONTRIBUTOR: 1
  OWNER: 1
  COLLABORATOR: 1
blockingLabels:
  - wip
```
![image](https://user-images.githubusercontent.com/12082478/109960382-fb947700-7ce8-11eb-9157-8ed0d6d3dcba.png)

And 
![image](https://user-images.githubusercontent.com/12082478/109960415-06e7a280-7ce9-11eb-90ac-16f7debd5897.png)

I don't understand why it is not checked.

**Comment by stefdelec** [comment]
I even tried 
![image](https://user-images.githubusercontent.com/12082478/109962267-457e5c80-7ceb-11eb-9a0d-151c3a8f0901.png)

**Comment by AnandChowdhary** [comment]
@bobvanderlinden I'm having the same issue, but I'm certain I'm doing something wrong. Any chance you have a few moments to help us reproduce, triage, and fix this? Thanks a ton for a great project!

**Comment by bobvanderlinden** [comment]
What is the exact role of the reviewer? You can check this using:

```
query { 
  repository(name: ***, owner: ***) {
    pullRequest(number: 123) {
      reviews(first: 1) {
        nodes {
          authorAssociation
        }
      }
    }
  }
}
```

Is it one of: https://github.com/bobvanderlinden/probot-auto-merge/blob/3da1900ecebbfc9b80e1112d4157149279f6fcaa/src/association.ts#L4-L10

That said, I would also recommend checking out GitHub merge queues. It is in beta, but covers most use-cases of probot-auto-merge without self-hosting an application.

**Comment by AnandChowdhary** [comment]
Thanks @bobvanderlinden!

<details>
<summary>The API response says `CONTRIBUTOR`</summary>

```json
{
  "data": {
    "repository": {
      "pullRequest": {
        "reviews": {
          "nodes": [
            {
              "authorAssociation": "CONTRIBUTOR"
            }
          ]
        }
      }
    }
  }
}
```
</details>

<details>
<summary>And the `github/auto-merge.yml` says 1 for contributor:</summary>

```yaml
updateBranch: true
deleteBranchAfterMerge: true
reportStatus: true
minApprovals:
  OWNER: 0
  MEMBER: 1
  COLLABORATOR: 1
  CONTRIBUTOR: 1
  FIRST_TIMER: 1
  FIRST_TIME_CONTRIBUTOR: 1
  NONE: 1
blockingLabels:
  - blocked
mergeCommitMessage: "{title} (#{number})"
```
</details>

And here's me approving :)

<img width="917" alt="CleanShot 2022-07-12 at 13 08 53@2x" src="https://user-images.githubusercontent.com/2841780/178435774-1d42e4a1-74fe-42c2-aa6b-5fee77c61a6c.png">
